name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: echo hello world > hello.txt


# name: Run tests
# on: push
# jobs:
#   run_tests:
#     name: Install requirements and run tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Update
#         run: sudo apt update
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - name: Install pip
#         run: sudo apt install python3-pip
#       - name: Install requirements
#         run: pip install -r requirements.txt
#       - name: Run tests
#         run: python manage.py test